<?php

/**
 * ProcessWire Currency Textformatter.
 *
 * Copyright 2016 Stephen Dickinson
 *
 * The above copyright notice and the following permissions and disclaimer shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

class TextformatterCurrency extends WireData implements Module, ConfigurableModule
{
    /**
     * Default settings used by this module
     */
    static protected $defaultSettings = array(
        'tfc_use_browser_locale'   => 1,
        'tfc_currency_glue_string' => ' + ',
        'tfc_currency_separator'   => '|',
        'tfc_locale'               => 'en_GB',
    );


    public static function getModuleInfo()
    {
        return array(
            'title'     => __('Textformatter for currencies.'),
            'version'   => '1.1.0',
            'summary'   => __('Provides a locale-aware currency formatter for text fields.'),
            'permanent' => false,
            'singular'  => true,
            'author'    => 'Netcarver',
        );
    }


    /**
     * Set the locale to use.
     *
     * If one of the key strings "browser"|"header"|"headers" is passed in, it will cause the module to attempt to use
     * the browser's httpAccept headers to define the locale to use.
     *
     * Providing a string other than these will turn off accept header searching and use the given string as the locale.
     *
     * @param string $locale A non-empty string either "browser"|"header"|"headers"|<locale string>
     * @return bool true if the locale was accepted and set
     */
    public function useLocale($locale) {
        if (!is_string($locale) || empty(trim($locale))) {
            return false;
        }

        $locale = trim($locale);

        if (in_array(strtolower($locale), array('browser', 'header', 'headers'))) {
            $this->tfc_use_browser_locale = '1';
        } else {
            $this->tfc_use_browser_locale = '0';
            $this->tfc_locale = $locale;
        }

        return true;
    }


    /**
     * Old style format() method
     *
     * NB: Changes the input $str variable
     */
    public function format(&$str) {
        if (!strlen($str)) return;
        $str = $this->formatCurrency($str);
    }


    /**
     * New style format method
     *
     * NB: Changes the input $str variable
     */
    public function formatValue(Page $page, Field $field, &$str) {
        if (!strlen($str)) return;
        $str = $this->formatCurrency($str);
    }


    /**
     * Common format method
     */
    public function formatCurrency($str) {
        if (!strlen($str)) return '';

        $locale = ($this->tfc_locale) ?: 'en';
        if ($this->tfc_use_browser_locale) {
            $locale = locale_accept_from_http($_SERVER['HTTP_ACCEPT_LANGUAGE']);
        }
        $fmt = new \NumberFormatter($locale, \NumberFormatter::CURRENCY);
        $currencies = explode(trim($this->tfc_currency_separator), $str);
        $out = array();
        foreach ($currencies as $currency_and_amount) {
            list($currency, $amount) = explode(' ', trim($currency_and_amount));
            $st = $fmt->formatCurrency(trim($amount), trim($currency));
            $st = str_replace('-', '−', $st);
            $out[] = "{$st}";
        }
        return implode(" {$this->tfc_currency_glue_string} ", $out);
    }


    /**
     * Build a form allowing configuration of this Module
     */
    static public function getModuleConfigInputfields(array $data)
    {
        $fields = new InputfieldWrapper();
        $data   = array_merge(self::$defaultSettings, $data);
        $m      = wire('modules');

        $f = $m->get('InputfieldRadios');
        $f->attr('name', 'tfc_use_browser_locale');
        $f->label = __("Use the visiting browsers prefered locale when possible?");
        $f->addOption(1, __('Yes, use the browser locale to determine how to format currency.'));
        $f->addOption(0, __('No'));
        $f->required = 1;
        $f->value = $data['tfc_use_browser_locale'];
        $f->columnWidth = 50;
        $fields->add($f);

        $f = $m->get('InputfieldText');
        $f->attr('name', 'tfc_locale');
        $f->label = __("What locale should be used for formatting if the browser locale is not used?");
        $f->value = $data['tfc_locale'];
        $f->columnWidth = 50;
        $fields->add($f);

        $f = $m->get('InputfieldText');
        $f->attr('name', 'tfc_currency_separator');
        $f->label = __("Separator for multiple unformatted currencies");
        $f->value = $data['tfc_currency_separator'];
        $f->columnWidth = 50;
        $f->required = 1;
        $fields->add($f);

        $f = $m->get('InputfieldText');
        $f->attr('name', 'tfc_currency_glue_string');
        $f->label = __("Joiner for multiple formatted currencies");
        $f->value = $data['tfc_currency_glue_string'];
        $f->columnWidth = 50;
        $f->required = 1;
        $fields->add($f);

        return $fields;
    }
}
